---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cortex-webapp
  namespace: bharatradar
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: cortex.bharatradar.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cortex-webapp
                port:
                  number: 8081
  tls:
    - hosts:
        - cortex.bharatradar.com
      secretName: cortex-webapp-tls
