resources:
- haproxy/default
- resources.yaml
- telegram-bot.yaml
- ai-agents.yaml
- flight-tracker.yaml
- schedule-downloader-cronjob.yaml
- api/default
- external/default
- hub/default
- ingest/default
- mlat/default
- mlat-map/default
- planes/default
- reapi/default
- history/default
- website/default
namespace: bharatradar
