resources:
- haproxy/default
- ingest/default
- external/default
- hub/default
- mlat/default
- reapi/default
- planes/default
- mlat-map/default
- api/default
- history/default
- website/default
- resources.yaml
namespace: bharatradar
