-- BharatRadar Airport Seed Data
-- 121 Indian airports

INSERT INTO airports (icao, iata, name, city, state, region, lat, lon, elev, type, timezone, hub_for, metro_connected, mag_var_w) VALUES
('VIDP', 'DEL', E'Indira Gandhi International Airport', E'New Delhi', E'Delhi', E'North', 28.566, 77.103, 777, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], true, 0.5),
('VIJW', 'DXN', E'Noida International Airport', E'Jewar (Noida)', E'Uttar Pradesh', E'North', 28.149, 77.675, 800, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIAR', 'ATQ', E'Sri Guru Ram Dass Jee International Airport', E'Amritsar', E'Punjab', E'North', 31.709, 74.797, 755, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VICG', 'IXC', E'Shaheed Bhagat Singh International Airport', E'Chandigarh', E'Chandigarh', E'North', 30.673, 76.788, 1012, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VISR', 'SXR', E'Sheikh ul-Alam International Airport', E'Srinagar', E'Jammu and Kashmir', E'North', 33.987, 74.774, 5377, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIJU', 'IXJ', E'Jammu Airport', E'Jammu', E'Jammu and Kashmir', E'North', 32.689, 74.838, 996, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VILH', 'IXL', E'Kushok Bakula Rimpochee Airport', E'Leh', E'Ladakh', E'North', 34.135, 77.546, 10682, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIDN', 'DED', E'Jolly Grant Airport', E'Dehradun', E'Uttarakhand', E'North', 30.189, 78.18, 1824, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VILK', 'LKO', E'Chaudhary Charan Singh International Airport', E'Lucknow', E'Uttar Pradesh', E'North', 26.76, 80.889, 404, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], true, 0.5),
('VEBN', 'VNS', E'Lal Bahadur Shastri International Airport', E'Varanasi', E'Uttar Pradesh', E'North', 25.451, 82.855, 266, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEAY', 'AYJ', E'Maharishi Valmiki International Airport', E'Ayodhya', E'Uttar Pradesh', E'North', 26.751, 82.155, 315, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIAL', 'IXD', E'Prayagraj Airport', E'Prayagraj', E'Uttar Pradesh', E'North', 25.439, 81.733, 322, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIGG', 'DHM', E'Kangra Airport', E'Dharamshala', E'Himachal Pradesh', E'North', 32.164, 76.262, 2525, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIBY', 'BEK', E'Bareilly Airport', E'Bareilly', E'Uttar Pradesh', E'North', 28.421, 79.452, 564, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEGK', 'GOP', E'Mahayogi Gorakhnath Airport', E'Gorakhpur', E'Uttar Pradesh', E'North', 26.74, 83.449, 259, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIPT', 'PGH', E'Pantnagar Airport', E'Pantnagar', E'Uttarakhand', E'North', 29.032, 79.384, 760, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIBR', 'KUU', E'Kullu-Manali Airport', E'Kullu', E'Himachal Pradesh', E'North', 31.876, 77.154, 3600, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VISM', 'SLV', E'Shimla Airport', E'Shimla', E'Himachal Pradesh', E'North', 31.081, 77.068, 5000, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIAH', 'HRH', E'Aligarh Airport', E'Aligarh', E'Uttar Pradesh', E'North', 27.882, 78.114, 600, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIDX', 'HDO', E'Hindon Airport', E'Hindon', E'Uttar Pradesh', E'North', 28.708, 77.359, 700, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOBL', 'BLR', E'Kempegowda International Airport', E'Bangalore', E'Karnataka', E'South', 13.198, 77.706, 3000, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], true, 0.5),
('VOHS', 'HYD', E'Rajiv Gandhi International Airport', E'Hyderabad', E'Telangana', E'South', 17.24, 78.429, 2024, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOMM', 'MAA', E'Chennai International Airport', E'Chennai', E'Tamil Nadu', E'South', 12.99, 80.169, 52, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], true, 0.5),
('VOCI', 'COK', E'Cochin International Airport', E'Kochi', E'Kerala', E'South', 10.152, 76.39, 16, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOTV', 'TRV', E'Thiruvananthapuram International Airport', E'Thiruvananthapuram', E'Kerala', E'South', 8.482, 76.92, 15, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOCL', 'CCJ', E'Calicut International Airport', E'Kozhikode', E'Kerala', E'South', 11.136, 75.955, 343, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOML', 'IXE', E'Mangaluru International Airport', E'Mangaluru', E'Karnataka', E'South', 12.961, 74.89, 336, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOTR', 'TRZ', E'Tiruchirappalli International Airport', E'Tiruchirappalli', E'Tamil Nadu', E'South', 10.765, 78.709, 288, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOCB', 'CJB', E'Coimbatore International Airport', E'Coimbatore', E'Tamil Nadu', E'South', 11.03, 77.043, 1318, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOMD', 'IXM', E'Madurai Airport', E'Madurai', E'Tamil Nadu', E'South', 9.834, 78.093, 446, E'Customs', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOKN', 'CNN', E'Kannur International Airport', E'Kannur', E'Kerala', E'South', 11.917, 75.551, 335, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOTP', 'TIR', E'Tirupati Airport', E'Tirupati', E'Andhra Pradesh', E'South', 13.632, 79.543, 351, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOVZ', 'VTZ', E'Visakhapatnam Airport', E'Visakhapatnam', E'Andhra Pradesh', E'South', 17.721, 83.224, 15, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOBZ', 'VGA', E'Vijayawada Airport', E'Vijayawada', E'Andhra Pradesh', E'South', 16.53, 80.797, 82, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOKU', 'KJB', E'Uyyalawada Narasimha Reddy Airport', E'Kurnool', E'Andhra Pradesh', E'South', 15.795, 78.204, 1000, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VORY', 'RJA', E'Rajahmundry Airport', E'Rajahmundry', E'Andhra Pradesh', E'South', 17.11, 81.817, 151, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAHB', 'HBX', E'Hubballi Airport', E'Hubli', E'Karnataka', E'South', 15.361, 75.084, 2170, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VABM', 'IXG', E'Belagavi Airport', E'Belagavi', E'Karnataka', E'South', 15.859, 74.618, 2487, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOPC', 'PNY', E'Puducherry Airport', E'Pondicherry', E'Puducherry', E'South', 11.968, 79.81, 135, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOAT', 'AGX', E'Agatti Airport', E'Agatti', E'Lakshadweep', E'South', 10.824, 72.176, 13, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOJV', 'VDY', E'Jindal Vijaynagar Airport', E'Vidyanagar', E'Karnataka', E'South', 15.175, 76.635, 1565, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOMY', 'MYQ', E'Mysuru Airport', E'Mysuru', E'Karnataka', E'South', 12.231, 76.654, 2350, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOPB', 'IXZ', E'Veer Savarkar International Airport', E'Port Blair', E'Andaman and Nicobar Islands', E'South', 11.641, 92.73, 23, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOCP', 'CDP', E'Kadapa Airport', E'Kadapa', E'Andhra Pradesh', E'South', 14.51, 78.773, 430, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOSM', 'SXV', E'Salem Airport', E'Salem', E'Tamil Nadu', E'South', 11.777, 78.064, 1000, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VABB', 'BOM', E'Chhatrapati Shivaji Maharaj International Airport', E'Mumbai', E'Maharashtra', E'West', 19.089, 72.868, 37, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], true, 0.5),
('VANM', 'NMI', E'Navi Mumbai International Airport', E'Navi Mumbai', E'Maharashtra', E'West', 18.991, 73.064, 15, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], true, 0.5),
('VAPO', 'PNQ', E'Pune Airport', E'Pune', E'Maharashtra', E'West', 18.582, 73.919, 1936, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], true, 0.5),
('VAAH', 'AMD', E'Sardar Vallabhbhai Patel International Airport', E'Ahmedabad', E'Gujarat', E'West', 23.077, 72.634, 189, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], true, 0.5),
('VOGO', 'GOI', E'Dabolim Airport', E'Goa (Dabolim)', E'Goa', E'West', 15.38, 73.831, 150, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOGA', 'GOX', E'Manohar International Airport', E'Goa (Mopa)', E'Goa', E'West', 15.729, 73.87, 551, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIJP', 'JAI', E'Jaipur International Airport', E'Jaipur', E'Rajasthan', E'West', 26.824, 75.801, 1263, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VASU', 'STV', E'Surat International Airport', E'Surat', E'Gujarat', E'West', 21.114, 72.742, 16, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAHS', 'HSR', E'Rajkot International Airport', E'Hirasar (Rajkot)', E'Gujarat', E'West', 22.317, 71.011, 430, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIJO', 'JDH', E'Jodhpur Airport', E'Jodhpur', E'Rajasthan', E'West', 26.251, 73.048, 719, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAUD', 'UDR', E'Maharana Pratap Airport', E'Udaipur', E'Rajasthan', E'West', 24.617, 73.896, 1684, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIJR', 'JSA', E'Jaisalmer Airport', E'Jaisalmer', E'Rajasthan', E'West', 26.889, 70.865, 824, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAVO', 'BDQ', E'Vadodara Airport', E'Vadodara', E'Gujarat', E'West', 22.336, 73.219, 127, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAAU', 'IXU', E'Aurangabad Airport', E'Aurangabad', E'Maharashtra', E'West', 19.863, 75.396, 1911, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VASD', 'SAG', E'Shirdi Airport', E'Shirdi', E'Maharashtra', E'West', 19.683, 74.375, 1913, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAKP', 'KLH', E'Kolhapur Airport', E'Kolhapur', E'Maharashtra', E'West', 16.665, 74.289, 1978, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VABV', 'BHU', E'Bhavnagar Airport', E'Bhavnagar', E'Gujarat', E'West', 21.751, 72.185, 43, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VABJ', 'BHJ', E'Bhuj Airport', E'Bhuj', E'Gujarat', E'West', 23.287, 69.67, 268, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAKE', 'IXY', E'Kandla Airport', E'Kandla', E'Gujarat', E'West', 23.113, 70.101, 96, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAOZ', 'ISK', E'Nashik International Airport', E'Nasik', E'Maharashtra', E'West', 20.118, 73.913, 1900, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAPR', 'PBD', E'Porbandar Airport', E'Porbandar', E'Gujarat', E'West', 21.648, 69.657, 20, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAJM', 'JGA', E'Jamnagar Airport', E'Jamnagar', E'Gujarat', E'West', 22.479, 70.011, 70, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VADI', 'DIU', E'Diu Airport', E'Diu', E'Daman and Diu', E'West', 20.713, 70.92, 30, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIBK', 'BKB', E'Nal Airport', E'Bikaner', E'Rajasthan', E'West', 28.071, 73.205, 750, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOSR', 'SDW', E'Sindhudurg Airport', E'Sindhudurg', E'Maharashtra', E'West', 16.002, 73.524, 200, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAND', 'NDC', E'Shri Guru Gobind Singh Ji Airport', E'Nanded', E'Maharashtra', E'West', 19.181, 77.318, 1200, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAID', 'IDR', E'Devi Ahilya Bai Holkar Airport', E'Indore', E'Madhya Pradesh', E'Central', 22.721, 75.801, 1850, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VANP', 'NAG', E'Dr. Babasaheb Ambedkar International Airport', E'Nagpur', E'Maharashtra', E'Central', 21.092, 79.047, 1012, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], true, 0.5),
('VARP', 'RPR', E'Swami Vivekananda Airport', E'Raipur', E'Chhattisgarh', E'Central', 21.18, 81.738, 1040, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAGL', 'GWL', E'Rajmata Vijayaraje Scindia Airport', E'Gwalior', E'Madhya Pradesh', E'Central', 26.293, 78.227, 617, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEKO', 'HJR', E'Khajuraho Airport', E'Khajuraho', E'Madhya Pradesh', E'Central', 24.817, 79.918, 700, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VARW', 'REW', E'Rewa Airport', E'Rewa', E'Madhya Pradesh', E'Central', 24.526, 81.282, 1000, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEBU', 'PAB', E'Bilasa Devi Kevat Airport', E'Bilaspur', E'Chhattisgarh', E'Central', 21.987, 82.11, 900, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEJR', 'JGB', E'Maa Danteshwari Airport', E'Jagdalpur', E'Chhattisgarh', E'Central', 19.074, 82.034, 1800, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VECC', 'CCU', E'Netaji Subhash Chandra Bose International Airport', E'Kolkata', E'West Bengal', E'East', 22.654, 88.446, 16, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], true, 0.5),
('VEBS', 'BBI', E'Biju Patnaik International Airport', E'Bhubaneswar', E'Odisha', E'East', 20.244, 85.817, 140, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEPT', 'PAT', E'Jay Prakash Narayan Airport', E'Patna', E'Bihar', E'East', 25.591, 85.088, 170, E'Customs', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VERC', 'IXR', E'Birsa Munda Airport', E'Ranchi', E'Jharkhand', E'East', 23.314, 85.322, 2120, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEDH', 'DBR', E'Darbhanga Airport', E'Darbhanga', E'Bihar', E'East', 26.191, 85.918, 150, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEBD', 'IXB', E'Bagdogra International Airport', E'Bagdogra', E'West Bengal', E'East', 26.681, 88.328, 412, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEDO', 'DGH', E'Deoghar Airport', E'Deoghar', E'Jharkhand', E'East', 24.44, 86.702, 830, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEJH', 'JRG', E'Veer Surendra Sai Airport', E'Jharsuguda', E'Odisha', E'East', 21.914, 84.053, 730, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEGY', 'GAY', E'Gaya Airport', E'Gaya', E'Bihar', E'East', 24.748, 84.951, 377, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VERK', 'RRK', E'Rourkela Airport', E'Rourkela', E'Odisha', E'East', 22.256, 84.814, 650, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEGT', 'GAU', E'Lokpriya Gopinath Bordoloi International Airport', E'Guwahati', E'Assam', E'North-East', 26.106, 91.585, 162, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEIM', 'IMF', E'Bir Tikendrajit International Airport', E'Imphal', E'Manipur', E'North-East', 24.759, 93.896, 2542, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEAT', 'IXA', E'Maharaja Bir Bikram Airport', E'Agartala', E'Tripura', E'North-East', 23.886, 91.24, 47, E'International', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEHO', 'HGI', E'Donyi Polo Airport', E'Itanagar', E'Arunachal Pradesh', E'North-East', 26.963, 93.652, 350, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEKU', 'IXS', E'Silchar Airport', E'Silchar', E'Assam', E'North-East', 24.912, 92.978, 107, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEMN', 'DIB', E'Dibrugarh Airport', E'Dibrugarh', E'Assam', E'North-East', 27.484, 95.017, 362, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEJT', 'JRH', E'Jorhat Airport', E'Jorhat', E'Assam', E'North-East', 26.731, 94.175, 284, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEBI', 'SHL', E'Shillong Airport', E'Shillong', E'Meghalaya', E'North-East', 25.703, 91.978, 2910, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEMR', 'DMU', E'Dimapur Airport', E'Dimapur', E'Nagaland', E'North-East', 25.883, 93.771, 487, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VELP', 'AJL', E'Lengpui Airport', E'Aizawl', E'Mizoram', E'North-East', 23.84, 92.619, 1320, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VESK', 'PYG', E'Pakyong Airport', E'Pakyong', E'Sikkim', E'North-East', 27.23, 88.587, 4646, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIAG', 'AGR', E'Agra Airport / Pandit Deen Dayal Upadhyay Airport', E'Agra', E'Uttar Pradesh', E'North', 27.155, 77.960, 551, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VABP', 'BHO', E'Raja Bhoj Airport', E'Bhopal', E'Madhya Pradesh', E'Central', 23.287, 77.337, 1732, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIBT', 'BUP', E'Bathinda Airport / Bhisiana Air Force Station', E'Bathinda', E'Punjab', E'North', 30.270, 74.755, 662, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VECO', 'COH', E'Cooch Behar Airport', E'Cooch Behar', E'West Bengal', E'East', 26.331, 89.468, 138, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAKS', 'IXK', E'Keshod Airport', E'Keshod', E'Gujarat', E'West', 21.317, 70.270, 167, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEPG', 'IXT', E'Pasighat Airport', E'Pasighat', E'Arunachal Pradesh', E'North-East', 28.068, 95.332, 515, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEJS', 'IXW', E'Sonari Airport', E'Jamshedpur', E'Jharkhand', E'East', 22.813, 86.168, 479, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAJL', 'JLG', E'Jalgaon Airport', E'Jalgaon', E'Maharashtra', E'West', 20.954, 75.635, 801, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIKA', 'KNU', E'Kanpur Airport', E'Kanpur', E'Uttar Pradesh', E'North', 26.402, 80.412, 400, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIKG', 'KQH', E'Kishangarh Airport', E'Ajmer', E'Rajasthan', E'West', 26.602, 74.815, 1400, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VILD', 'LUH', E'Sahnewal Airport', E'Ludhiana', E'Punjab', E'North', 30.854, 75.956, 834, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIMB', 'MZS', E'Moradabad Airport', E'Moradabad', E'Uttar Pradesh', E'North', 28.819, 78.924, 637, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEJP', 'PYB', E'Jeypore Airport', E'Jeypore', E'Odisha', E'East', 18.880, 82.553, 1965, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEDG', 'RDP', E'Kazi Nazrul Islam Airport', E'Durgapur', E'West Bengal', E'East', 23.621, 87.240, 312, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VERU', 'RUP', E'Rupsi Airport', E'Rupsi', E'Assam', E'North-East', 26.139, 89.908, 131, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOTK', 'TCR', E'Tuticorin Airport', E'Tuticorin', E'Tamil Nadu', E'South', 8.724, 78.020, 129, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VETJ', 'TEI', E'Tezu Airport', E'Tezu', E'Arunachal Pradesh', E'North-East', 27.942, 96.133, 769, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VETE', 'TEZ', E'Tezpur Airport', E'Tezpur', E'Assam', E'North-East', 26.632, 92.785, 240, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEZO', 'ZER', E'Ziro Airport', E'Ziro', E'Arunachal Pradesh', E'North-East', 27.587, 93.827, 5300, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAJB', 'JLR', E'Jabalpur Airport / Dumna Airport', E'Jabalpur', E'Madhya Pradesh', E'Central', 23.178, 80.052, 1624, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VELR', 'IXI', E'Lilabari Airport', E'Keshod', E'Gujarat', E'West', 27.298, 94.097, 333, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIHR', 'HSS', E'Hisar Airport', E'Hisar', E'Haryana', E'North', 29.180, 75.753, 700, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VERH', 'RQY', E'Raigarh Airport', E'Raigarh', E'Chhattisgarh', E'Central', 21.854, 83.404, 1000, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEPU', 'PXN', E'Purnea Airport', E'Purnia', E'Bihar', E'East', 25.760, 87.406, 125, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VIAX', 'AIP', E'Adampur Airport', E'Jalandhar', E'Punjab', E'North', 31.433, 75.759, 775, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VASL', 'SSE', E'Solapur Airport', E'Solapur', E'Maharashtra', E'West', 17.626, 75.934, 1583, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAGD', 'GDB', E'Birsi Airport', E'Gondia', E'Maharashtra', E'West', 21.480, 80.309, 1020, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VAAM', 'AVR', E'Amravati Airport', E'Amravati', E'Maharashtra', E'West', 20.852, 77.720, 1000, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VOBR', 'IXX', E'Bidar Airport', E'Bidar', E'Karnataka', E'South', 17.908, 77.487, 2178, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VEUK', 'UKE', E'Utkela Airport', E'Kalahandi', E'Odisha', E'East', 20.000, 83.181, 645, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5),
('VADT', 'DPP', E'Datia Airport', E'Datia', E'Madhya Pradesh', E'Central', 25.660, 78.471, 900, E'Domestic', E'Asia/Kolkata', ARRAY[]::TEXT[], false, 0.5);
